---
- name: Configure web server
  hosts: all
  become: true

  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        update_cache: yes

    - name: Copy index.html file
      copy:
        src: files/
        dest: /var/www/html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
